### ISSUE TITLE
Spinner didn't clear previous message if it is too long

### ISSUE THREAD

**Issue by cheahkhing** [nathanpeck/clui#6]
Hi, thanks for your great clui module, i like it a lot. :+1: 

Anyway, here's one issue i found when i tried the spinner.

If you update the message using spinner.message('some very very long message');
then spinner.message('short message'), you will see that your output will get tangled up. Because the short message is printed over the old message, i think it should clear the line before spitting out the new message.

**BTW, your documentationi says spinner.update(), but there's no such method, i see the code then I notice it's spinner.message().

**Comment by thelaw44** [comment]
You guys have a very dirty documentation, but your module is awesome.

**Comment by luiseduardobrito** [comment]
One year, still no response?

**Comment by artokun** [comment]
I'll first update the readme and take a look at clearing the line on update. Confirmed bug.

**Comment by artokun** [comment]
Ref: https://github.com/nathanpeck/clui/pull/7

**Comment by artokun** [comment]
Merged in
